testthat::test_that("portfolio modal CRUD is independent from single bond sidebar", {
  original <- getwd(); setwd(normalizePath(file.path("..", ".."))); on.exit(setwd(original), add = TRUE)
  for (module in c("presentation", "ui", "server")) source(file.path("R", paste0(module, ".R")), local = TRUE)
  shiny::testServer(board_server, {
    session$setInputs(weighting = "market", portfolio_selected_shocks = as.character(standard_shocks), portfolio_custom_shock = 75)
    testthat::expect_equal(nrow(universe()), 5)
    testthat::expect_equal(nrow(portfolio_scenarios()), 12)
    testthat::expect_true(nchar(output$portfolio_kpis$html) > 0)
    testthat::expect_true(nchar(output$portfolio_input) > 0)
    testthat::expect_true(nchar(output$portfolio_plot) > 0)
    testthat::expect_true(nchar(output$portfolio_position_shocks) > 0)
    session$setInputs(weighting = "equal")
    testthat::expect_equal(portfolio()$positions$weight_pct, rep(20, 5))
    before <- portfolio()$gross_value
    session$setInputs(nominal = -1, coupon = -1, clean_price = -1, settlement = as.Date("2035-01-01"), maturity = as.Date("2030-01-01"), frequency = "2", direction = "price")
    testthat::expect_equal(portfolio()$gross_value, before)
    session$setInputs(weighting = "market", add_bond = 1)
    session$setInputs(pf_name = "Independent Portfolio Bond", pf_isin = "", pf_position = "Short", pf_nominal = 100000,
      pf_coupon = 3, pf_clean = 99, pf_settlement = as.Date("2026-10-01"), pf_maturity = as.Date("2033-10-01"), pf_frequency = "1", save_bond = 1)
    testthat::expect_equal(nrow(universe()), 6)
    testthat::expect_equal(tail(universe()$position, 1), "Short")
    session$setInputs(portfolio_input_rows_selected = 6, edit_bond = 1)
    testthat::expect_equal(editing(), 6)
    session$setInputs(pf_name = "Edited Bond", pf_nominal = 250000, pf_position = "Long", save_bond = 2)
    testthat::expect_equal(universe()$nominal[6], 250000)
    testthat::expect_equal(universe()$position[6], "Long")
    session$setInputs(pf_nominal = -2, save_bond = 3)
    testthat::expect_equal(universe()$nominal[6], 250000)
    testthat::expect_match(modal_error(), "Nominal")
    session$setInputs(remove_bond = 1)
    testthat::expect_equal(nrow(universe()), 5)
    session$setInputs(add_bond = 2, pf_nominal = 100000, pf_position = "Short")
    for (i in 4:8) session$setInputs(save_bond = i)
    testthat::expect_equal(nrow(universe()), 10)
    session$setInputs(add_bond = 3, save_bond = 9)
    testthat::expect_equal(nrow(universe()), 10)
    testthat::expect_match(form_error(), "Maximal zehn")
    testthat::expect_match(modal_error(), "Maximal zehn")
    session$setInputs(clear_portfolio = 1)
    testthat::expect_equal(nrow(universe()), 0)
    testthat::expect_null(output$portfolio_kpis)
    testthat::expect_true(nchar(output$portfolio_input) > 0)
    session$setInputs(add_bond = 4, save_bond = 10)
    testthat::expect_equal(nrow(universe()), 1)
    session$setInputs(portfolio_input_rows_selected = 1, remove_bond = 2)
    testthat::expect_equal(nrow(universe()), 0)
    session$setInputs(reset_demo = 1)
    testthat::expect_equal(nrow(universe()), 5)
    session$setInputs(portfolio_selected_shocks = c("-100", "100"), portfolio_custom_shock = 42)
    testthat::expect_equal(portfolio_shock_values(), c(-100, 42, 100))
    html <- as.character(board_ui())
    testthat::expect_false(grepl("Sidebar-Bond|Erste drei Positionen|Netto Modified|Netto Convexity", html))
    testthat::expect_match(html, "Bond bearbeiten")
    testthat::expect_match(html, "Demoportfolio laden")
    table <- board_table(data.frame(value = 1:4))
    testthat::expect_false(table$x$options$lengthChange)
    testthat::expect_false(table$x$options$paging)
  })
})


testthat::test_that("two-tab single bond valuation retains eight core KPIs", {
  original <- getwd(); setwd(normalizePath(file.path("..", ".."))); on.exit(setwd(original), add = TRUE)
  for (module in c("presentation", "ui", "server")) source(file.path("R", paste0(module, ".R")), local = TRUE)
  html <- as.character(board_ui())
  testthat::expect_match(html, 'data-value="Bond Valuation"')
  testthat::expect_match(html, 'data-value="Portfolio Simulation"')
  testthat::expect_length(regmatches(html, gregexpr('data-toggle="tab"', html))[[1]], 2)
  testthat::expect_false(grepl('Risk-Analyse|risk_note|local_risk|bond_shock_plot|id="custom_shock"', html))
  shiny::testServer(board_server, {
    session$setInputs(nominal = 100000, coupon = 4, settlement = as.Date("2026-10-15"), maturity = as.Date("2032-04-01"),
      frequency = "2", bond_name = "Single Bond", direction = "price", clean_price = 98.5, yield = 4.3,
      weighting = "market", portfolio_selected_shocks = as.character(standard_shocks), portfolio_custom_shock = 75)
    a <- analysis()
    testthat::expect_equal(a$clean, 98.5, tolerance = 1e-8)
    testthat::expect_gt(a$accrued, 0)
    testthat::expect_equal(a$clean + a$accrued, a$dirty)
    testthat::expect_true(all(is.finite(unlist(a[c("yield", "clean", "dirty", "accrued", "macaulay", "modified", "dv01", "convexity")]))))
    card_html <- output$bond_kpis$html
    for (label in c("YTM", "Clean Price", "Dirty Price", "Accrued Interest", "Macaulay Duration", "Modified Duration", "DV01", "Convexity")) testthat::expect_match(card_html, label)
    testthat::expect_true(nchar(output$price_curve) > 0)
    testthat::expect_false(any(c("dv01_full", "value_down", "value_up") %in% names(a)))
    original_gross <- portfolio()$gross_value
    session$setInputs(direction = "yield", yield = 5)
    testthat::expect_equal(analysis()$yield, .05)
    testthat::expect_equal(portfolio()$gross_value, original_gross)
    session$setInputs(direction = "price", clean_price = -1)
    testthat::expect_error(analysis(), "Clean Price")
    testthat::expect_equal(portfolio()$gross_value, original_gross)
  })
})
