example_positions <- function(n = 5) data.frame(name = paste("Bond", seq_len(n)), isin = "", position = rep(c("Long", "Short"), length.out = n), nominal = seq(100000, by = 20000, length.out = n), coupon = seq(2, by = .25, length.out = n), clean_price = seq(95, by = 1, length.out = n), settlement = "2026-10-01", maturity = paste0(2028 + seq_len(n), "-10-01"), frequency = 1)
testthat::test_that("explicit positions and gross weighted risks survive reordering", {
  d <- example_positions(); p <- portfolio_from_data(d, "market")
  testthat::expect_equal(p$positions$position, d$position)
  testthat::expect_equal(p$positions$nominal, d$nominal)
  testthat::expect_equal(sum(p$positions$weight_pct), 100)
  testthat::expect_equal(p$positions$weight_pct, abs(p$positions$market_value) / p$gross_value * 100)
  testthat::expect_equal(p$gross_value, p$long_value + p$short_value)
  testthat::expect_equal(p$market_value, p$long_value - p$short_value)
  testthat::expect_equal(p$dv01, sum(p$positions$dv01))
  testthat::expect_equal(p$gross_dv01, sum(abs(p$positions$dv01)))
  testthat::expect_equal(p$modified, sum(abs(p$positions$market_value) * p$positions$modified) / p$gross_value)
  testthat::expect_equal(p$convexity, sum(abs(p$positions$market_value) * p$positions$convexity) / p$gross_value)
  reordered <- portfolio_from_data(d[c(5, 2, 1, 4, 3), ], "market")
  testthat::expect_equal(reordered$positions$position, d$position[c(5, 2, 1, 4, 3)])
  testthat::expect_equal(reordered$dv01, p$dv01)
  testthat::expect_equal(reordered$market_value, p$market_value)
})
testthat::test_that("equal weighting uses equal market values and preserves user inputs", {
  d <- example_positions(); original <- d; p <- portfolio_from_data(d, "equal")
  testthat::expect_equal(p$positions$weight_pct, rep(20, 5))
  testthat::expect_equal(abs(p$positions$market_value), rep(p$gross_value / 5, 5))
  testthat::expect_equal(d, original)
  testthat::expect_equal(p$gross_value, portfolio_from_data(d, "market")$gross_value)
})
testthat::test_that("opposite identical positions hedge without singular risk metrics", {
  d <- example_positions(1); d <- rbind(d, d); d$position <- c("Long", "Short")
  p <- portfolio_from_data(d)
  testthat::expect_equal(p$market_value, 0)
  testthat::expect_equal(p$dv01, 0)
  testthat::expect_gt(p$gross_dv01, 0)
  testthat::expect_true(is.finite(p$modified))
  testthat::expect_true(is.finite(p$convexity))
  s <- portfolio_shocks(p)
  testthat::expect_equal(s$full_eur, rep(0, length(standard_shocks)))
  testthat::expect_equal(s$duration_eur, rep(0, length(standard_shocks)))
  detail <- portfolio_position_shocks(p, 100)
  testthat::expect_equal(detail$full_eur[1], -detail$full_eur[2])
  testthat::expect_lt(detail$full_eur[1], 0)
  testthat::expect_gt(detail$full_eur[2], 0)
})
testthat::test_that("portfolio shock results equal sum of signed position repricing", {
  for (method in c("equal", "market")) {
    p <- portfolio_from_data(example_positions(), method)
    shocks <- c(-200, -50, 0, 25, 100, 200)
    aggregate <- portfolio_shocks(p, shocks); detail <- portfolio_position_shocks(p, shocks)
    for (key in c("duration_eur", "convexity_eur", "full_eur")) {
      sums <- vapply(shocks, function(s) sum(detail[[key]][detail$shock_bp == s]), numeric(1))
      testthat::expect_equal(aggregate[[key]], sums)
    }
    expected <- sum(vapply(seq_along(p$bonds), function(i) p$signs[i] * price_bond(p$bonds[[i]], p$analyses[[i]]$yield + .01)$market_value, numeric(1))) - p$market_value
    testthat::expect_equal(aggregate$full_eur[5], expected)
    testthat::expect_equal(aggregate$full_pct[5], expected / p$gross_value * 100)
  }
})
testthat::test_that("one through ten positions can be added and eleventh is rejected", {
  d <- empty_portfolio()
  for (i in 1:10) d <- portfolio_upsert(d, example_positions(10)[i, ])
  testthat::expect_equal(nrow(d), 10)
  testthat::expect_equal(nrow(portfolio_from_data(d)$positions), 10)
  testthat::expect_error(portfolio_upsert(d, example_positions(1)), "Maximal zehn")
  testthat::expect_error(portfolio_from_data(rbind(d, d[1, ])), "1 bis 10")
  row <- d[1, ]; row$position <- "Short"; row$name <- "Changed"
  updated <- portfolio_upsert(d, row, 1)
  testthat::expect_equal(updated$position[1], "Short")
  testthat::expect_equal(updated$name[1], "Changed")
  testthat::expect_equal(nrow(portfolio_from_data(d[1, ])$positions), 1)
  row$position <- "Invalid"
  testthat::expect_error(portfolio_upsert(d, row, 1), "Long oder Short")
  row <- d[1, ]; row$settlement <- "2026-10-02"
  testthat::expect_error(portfolio_upsert(d[1:5, ], row), "gemeinsames Settlement")
  testthat::expect_error(portfolio_from_data(empty_portfolio()), "1 bis 10")
})
testthat::test_that("demo has at least five explicitly positioned public bank bonds", {
  d <- read.csv(file.path("..", "..", "data", "demo_portfolio.csv"))
  testthat::expect_gte(nrow(d), 5)
  testthat::expect_true(all(d$position %in% c("Long", "Short")))
  testthat::expect_true(all(grepl("^https://", d$source_url)))
  testthat::expect_true(all(d$issue_volume_eur >= 1e9))
  testthat::expect_equal(sum(portfolio_from_data(d)$positions$weight_pct), 100)
})
